# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: >
  This default Docker image is highly cached on CircleCI and contains most necessary tools needed for Gradle related projects.
docker:
  - image: 'cimg/openjdk:<<parameters.tag>>'
parameters:
  tag:
    default: "17.0"
    description: >
      Pick a specific cimg/openjdk image tag:
      https://hub.docker.com/r/cimg/openjdk/tags
    type: string
